version: "3"
volumes:
  remote-data:
    name: remote-data

services:
  backend:
    image: suterdev/remoter.backend:0.1.4
    restart: always
    environment:
      APP_KEY: YOURKEYHERE
      GF_ROOT_URL: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      GF_SERVE_FROM_SUB_PATH: "true"
    volumes:
      - grafana-data:/var/lib/grafana
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      
      
      
      
           
      
      

