version: "3"
volumes:
  remoter-data:
    name: remoter-data
    
services:
  backend:
    image: suterdev/remoter.backend:0.2.3
    restart: always
    environment:
      APP_KEY: YOURKEYHERE
      DATABASE_PATH: /data/data.db
    volumes:
      - remoter-data:/data
  
  frontend:
    image: suterdev/remoter.frontend:0.2.5
    restart: always
    environment:
      API_URL: /api
    volumes:
      - remoter-data:/data
    
    
  nginx:
    image: "nginx:1.23.3"
    ports:
      - "8443:8443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    links:
    - backend:backend
    - frontend:frontend

      
      

