apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    stack: remoter
spec:
  selector:
    matchLabels:
      app: postgres
      stack: remoter
  template:
    metadata:
      labels:
        app: postgres
        stack: remoter
    spec:
      volumes:
      - name: pvc-postgres
        persistentVolumeClaim:
          claimName: pvc-postgres
      - name: sql-init-db
        configMap:
          name: remoter-initial-db
      containers:
     
        - imagePullPolicy: Always
          name: postgres
          image: postgres:15.2
          envFrom:
          - configMapRef:
              name: remoter-config
          ports:
          - name: db
            protocol: TCP
            containerPort: 5432
          volumeMounts:
          - name: sql-init-db
            mountPath: /init.sql
            subPath: init.sql
          - name: sql-init-db
            mountPath: /docker-entrypoint-initdb.d/entry-init-db.sh
            subPath: entry-init-db.sh

            
          - mountPath: /data
            name: pvc-postgres
      restartPolicy: Always
  replicas: 1
